### ISSUE TITLE
(Direccion) SP_CrearDireccion

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#10]
Para este procedimiento debe tener el de parametro
- [ ] idUsuario
- [ ] Provincia
- [ ] Canton
- [ ] Distrito
- [ ] codPostal
- [ ] senalesExactas

y crear la direccion

**Comment by CrisPicado** [comment]
CREATE OR REPLACE PROCEDURE SP_CrearDireccion(
    p_idUsr IN NUMBER,
    p_provincia IN VARCHAR,
    p_canton IN VARCHAR,
    p_distrito IN VARCHAR,
    p_codPostal IN VARCHAR,
    p_senalesExactas IN VARCHAR
)
AS
    cuentaUsr NUMBER;
BEGIN
    
    --Valida si el usuario existe
    SELECT COUNT(*) INTO cuentaUsr 
    FROM Usuario u
    WHERE u.idUsuario = p_idUsr;
    
    IF cuentaUsr > 0 THEN

        INSERT INTO Direccion (idUsuario, provincia, canton, distrito, codPostal, senalesExactas)
        VALUES (p_idUsr, p_provincia, p_canton, p_distrito, p_codPostal, p_senalesExactas);
        
        DBMS_OUTPUT.PUT_LINE('Dirección creada con éxito.');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('No se ha encontrado el usuario indicado, no es posible crear la dirección.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al crear la dirección: ' || SQLERRM);
END;
