### ISSUE TITLE
(USUARIO) SP_LeerUsuarioUnico 

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#11]
Debe recibir como parametro 
-[ ] idUsuario

y retornar todos los datos del usuarios 
-[ ] idUsuario
-[ ] nombre
-[ ] primApellido
-[ ] segApellido
-[ ] cedula
-[ ] correo
-[ ] contrasenna
-[ ] NombreRol

**Comment by CrisPicado** [comment]
CREATE OR REPLACE PROCEDURE SP_LeerUsuarioUnico(
    p_idUsr IN NUMBER
) AS
    cuentaUsr NUMBER;
    v_idUsr NUMBER;
    v_nombre VARCHAR2(100);
    v_primApe VARCHAR2(100);
    v_segApe VARCHAR2(100);
    v_cedula NUMBER;
    v_correo VARCHAR2(100);
    v_contrasenna VARCHAR2(100);
    v_rol VARCHAR2(100);
BEGIN
    SELECT COUNT(*) INTO cuentaUsr
    FROM V_UsuariosConRol v
    WHERE v."ID Usuario" = p_idUsr;
    
    IF cuentaUsr > 0 THEN
        SELECT * 
        INTO v_idUsr, v_nombre, v_primApe, v_segApe, v_cedula, v_correo, v_contrasenna, v_rol
        FROM V_UsuariosConRol v
        WHERE v."ID Usuario" = p_idUsr;
        
        -- Mostrar los resultados
        DBMS_OUTPUT.PUT_LINE('ID Usuario: ' || v_idUsr);
        DBMS_OUTPUT.PUT_LINE('Nombre: ' || v_nombre);
        DBMS_OUTPUT.PUT_LINE('Primer Apellido: ' || v_primApe);
        DBMS_OUTPUT.PUT_LINE('Segundo Apellido: ' || v_segApe);
        DBMS_OUTPUT.PUT_LINE('Cédula: ' || v_cedula);
        DBMS_OUTPUT.PUT_LINE('Correo: ' || v_correo);
        DBMS_OUTPUT.PUT_LINE('Contraseña: ' || v_contrasenna);
        DBMS_OUTPUT.PUT_LINE('Rol: ' || v_rol);
    ELSE
        DBMS_OUTPUT.PUT_LINE('No se ha encontrado el usuario indicado.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error en procedimiento de lectura de usuario único: ' || SQLERRM);
END;
