### ISSUE TITLE
(Usuario) VIEW LeerUsuarios (todos)

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#12]
retornar todos los datos del usuarios 
-[ ] idUsuario
-[ ] nombre
-[ ] primApellido
-[ ] segApellido
-[ ] cedula
-[ ] correo
-[ ] contrasenna
-[ ] NombreRol

**Comment by CrisPicado** [comment]
Se da por finalizado el siguiente issue ya que es redundante al issue #8 (Usuario) View UsuariosPorRol #8

Es redundante porque la vista del issue 8 ya se encarga de devolver los datos de los usuarios existentes en la base de datos junto con el nombre del rol que tienen asignado, misma información que se está solicitando para este issue #12. 


--Vista UsuariosxRol
CREATE OR REPLACE VIEW V_UsuariosConRol AS
SELECT u.idUsuario "ID Usuario", u.nombre "Nombre", u.primApellido "Primer Apellido", u.segApellido "Segundo Apellido", u.cedula "Cédula", u.correo "Correo", u.contrasenna "Contraseña", r.nombre AS "Rol"
FROM Usuario u
INNER JOIN Rol r ON u.idRol = r.idRol;
