### ISSUE TITLE
(Usuario) Trigger VerUsuarioEditado

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#13]
Debe mostrar todos los datos del usuario Editado previamente

**Comment by CrisPicado** [comment]
CREATE OR REPLACE TRIGGER trg_insert_usuario
AFTER INSERT ON Usuario
FOR EACH ROW
DECLARE
    v_idUsr NUMBER;
    v_nombre VARCHAR2(100);
    v_primApe VARCHAR2(100);
    v_segApe VARCHAR2(100);
    v_cedula NUMBER;
    v_correo VARCHAR2(100);
    v_contrasenna VARCHAR2(100);
    v_idrol NUMBER;
BEGIN
    -- Recuperar los datos del usuario insertado
    v_idUsr := :NEW.idUsuario;
    v_nombre := :NEW.nombre;
    v_primApe := :NEW.primApellido;
    v_segApe := :NEW.segApellido;
    v_cedula := :NEW.cedula;
    v_correo := :NEW.correo;
    v_contrasenna := :NEW.contrasenna;
    v_idrol := :NEW.idrol;
    
    -- Mostrar los datos del usuario insertado
    DBMS_OUTPUT.PUT_LINE('Usuario insertado:');
    DBMS_OUTPUT.PUT_LINE('ID Usuario: ' || v_idUsr);
    DBMS_OUTPUT.PUT_LINE('Nombre: ' || v_nombre);
    DBMS_OUTPUT.PUT_LINE('Primer Apellido: ' || v_primApe);
    DBMS_OUTPUT.PUT_LINE('Segundo Apellido: ' || v_segApe);
    DBMS_OUTPUT.PUT_LINE('Cédula: ' || v_cedula);
    DBMS_OUTPUT.PUT_LINE('Correo: ' || v_correo);
    DBMS_OUTPUT.PUT_LINE('Contraseña: ' || v_contrasenna);
    DBMS_OUTPUT.PUT_LINE('ID Rol: ' || v_idrol);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error en el trigger trg_after_insert_usuario: ' || SQLERRM);
END;

CREATE OR REPLACE TRIGGER trg_update_usuario
AFTER UPDATE ON Usuario
FOR EACH ROW
DECLARE
    v_idUsr NUMBER;
    v_nombre VARCHAR2(100);
    v_primApe VARCHAR2(100);
    v_segApe VARCHAR2(100);
    v_cedula NUMBER;
    v_correo VARCHAR2(100);
    v_contrasenna VARCHAR2(100);
    v_idrol NUMBER;
BEGIN
    -- Recuperar los datos del usuario actualizado
    v_idUsr := :NEW.idUsuario;
    v_nombre := :NEW.nombre;
    v_primApe := :NEW.primApellido;
    v_segApe := :NEW.segApellido;
    v_cedula := :NEW.cedula;
    v_correo := :NEW.correo;
    v_contrasenna := :NEW.contrasenna;
    v_idrol := :NEW.idrol;
    
    -- Mostrar los datos del usuario actualizado
    DBMS_OUTPUT.PUT_LINE('Usuario editado:');
    DBMS_OUTPUT.PUT_LINE('ID Usuario: ' || v_idUsr);
    DBMS_OUTPUT.PUT_LINE('Nombre: ' || v_nombre);
    DBMS_OUTPUT.PUT_LINE('Primer Apellido: ' || v_primApe);
    DBMS_OUTPUT.PUT_LINE('Segundo Apellido: ' || v_segApe);
    DBMS_OUTPUT.PUT_LINE('Cédula: ' || v_cedula);
    DBMS_OUTPUT.PUT_LINE('Correo: ' || v_correo);
    DBMS_OUTPUT.PUT_LINE('Contraseña: ' || v_contrasenna);
    DBMS_OUTPUT.PUT_LINE('ID Rol: ' || v_idrol);
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error en el trigger trg_update_usuario: ' || SQLERRM);
END;
