### ISSUE TITLE
(ROL) SP_EditarRol

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#2]
Debe Crear un procedimiento que reciba como parametros:

 - [ ] idRol
 - [ ] Nombre

**Comment by CrisPicado** [comment]
CREATE OR REPLACE PROCEDURE SP_EditarRol
(
    p_idRol IN NUMERIC,
    p_nombre IN VARCHAR2
) AS
BEGIN
    --Valida ID nulo
    IF p_idRol IS NULL THEN
        DBMS_OUTPUT.PUT_LINE('Error: El ID ingresado es nulo.');
        RETURN;
    END IF;

    -- Valida rol null o vacío
    IF p_nombre IS NULL OR p_nombre = '' THEN
        DBMS_OUTPUT.PUT_LINE('Error: El nombre del rol es nulo o vacío.');
        RETURN;
    END IF;

    -- Verifica existencia del rol
    DECLARE
        cuenta NUMBER;
    BEGIN
        SELECT COUNT(*) INTO cuenta FROM Rol WHERE idRol = p_idRol;
        
        IF cuenta = 0 THEN
            DBMS_OUTPUT.PUT_LINE('Error: El rol no existe.');
        ELSE
            -- Actualiza el nombre del rol
            UPDATE Rol SET nombre = p_nombre WHERE idRol = p_idRol;
            DBMS_OUTPUT.PUT_LINE('El rol ha sido editado exitosamente.');
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Error al editar el rol: ' || SQLERRM);
    END;
END;
