### ISSUE TITLE
(Producto) SP_CrearProducto

### ISSUE THREAD

**Issue by Sebastian2207** [electromilitary45/PUFI_LenguajesBD#21]
Debe tener como parametros
-[ ] nombre
-[ ] descripcion
-[ ] stock
-[ ] estatus
-[ ] precio
-[ ] idTipoProducto

**Comment by CrisPicado** [comment]
CREATE OR REPLACE PROCEDURE SP_InsertarProducto(
    p_nombre IN VARCHAR2,
    p_descripcion IN VARCHAR2,
    p_stock IN NUMBER,
    p_estatus IN VARCHAR2,
    p_precio IN NUMBER,
    p_idTipoProducto IN NUMBER
)
AS
    v_contador NUMBER;
BEGIN
    -- Verificar si el idTipoProducto ya existe
    SELECT COUNT(*) INTO v_contador
    FROM TipoProducto v
    WHERE v.idtipoproducto = p_idTipoProducto;

    IF v_contador = 0 THEN
        DBMS_OUTPUT.PUT_LINE('El tipo de producto especificado no existe, no se puede crear el producto.');
    ELSE
        -- Insertar el producto
        INSERT INTO Producto(nombre, descripcion, stock, estatus, precio, idTipoProducto)
        VALUES (p_nombre, p_descripcion, p_stock, p_estatus, p_precio, p_idTipoProducto);
        
        DBMS_OUTPUT.PUT_LINE('Producto insertado con éxito.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al insertar el producto: ' || SQLERRM);
END;
