### ISSUE TITLE
(Producto) SP_EditarProducto

### ISSUE THREAD

**Issue by Sebastian2207** [electromilitary45/PUFI_LenguajesBD#23]
Debe de modificar los siguientes parametros
-[ ] nombre
-[ ] descripcion
-[ ] stock
-[ ] estatus
-[ ] precio
-[ ] idTipoProducto

**Comment by CrisPicado** [comment]
CREATE OR REPLACE PROCEDURE SP_EditarProducto(
    p_idProducto IN NUMBER,
    p_nombre IN VARCHAR2,
    p_descripcion IN VARCHAR2,
    p_stock IN NUMBER,
    p_estatus IN VARCHAR2,
    p_precio IN NUMBER,
    p_idTipoProducto IN NUMBER
)
AS
    v_contador NUMBER;
BEGIN
    -- Verificar si el idProducto existe
    SELECT COUNT(*) INTO v_contador
    FROM Producto
    WHERE IDPRODUCTO = p_idProducto;

    IF v_contador = 0 THEN
        DBMS_OUTPUT.PUT_LINE('El idProducto especificado no existe, no se puede editar el producto.');
    ELSE
        -- Actualizar el producto
        UPDATE Producto
        SET nombre = p_nombre,
            descripcion = p_descripcion,
            stock = p_stock,
            estatus = p_estatus,
            precio = p_precio,
            idTipoProducto = p_idTipoProducto
        WHERE IDPRODUCTO = p_idProducto;
        
        DBMS_OUTPUT.PUT_LINE('Producto editado con éxito.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al editar el producto: ' || SQLERRM);
END;
