### ISSUE TITLE
(Producto) SP_LeerProducto (UNICO)

### ISSUE THREAD

**Issue by Sebastian2207** [electromilitary45/PUFI_LenguajesBD#24]
Debe enviar por parametro:
-[ ] idProductos

Debe de mostrar los siguientes parametros:
-[ ] nombre
-[ ] descripcion
-[ ] stock
-[ ] estatus
-[ ] precio
-[ ] idTipoProducto

**Comment by CrisPicado** [comment]
CREATE OR REPLACE PROCEDURE SP_LeerProducto(
    p_idProducto IN NUMBER
) AS
    v_contador NUMBER;
    v_id NUMBER;
    v_categoria NUMBER;
    v_nombre VARCHAR(100);
    v_descipcion VARCHAR(200);
    v_stock NUMBER;
    v_status NUMBER;
    v_precio FLOAT;
BEGIN
    SELECT COUNT(*) INTO v_contador
    FROM Vista_LeerProductos p
    WHERE p."ID" = p_idProducto;
    
    IF v_contador > 0 THEN
        SELECT *
        INTO v_id, v_categoria, v_nombre, v_descipcion, v_stock, v_status, v_precio
        FROM Vista_LeerProductos p
        WHERE p."ID" = p_idProducto;
        DBMS_OUTPUT.PUT_LINE('---Datos del  producto---');
        DBMS_OUTPUT.PUT_LINE('ID: ' || v_id);
        DBMS_OUTPUT.PUT_LINE('ID Tipo Producto: ' || v_categoria);
        DBMS_OUTPUT.PUT_LINE('Nombre: ' || v_nombre);
        DBMS_OUTPUT.PUT_LINE('Descripción: ' || v_descipcion);
        DBMS_OUTPUT.PUT_LINE('Stock: ' || v_stock);
        DBMS_OUTPUT.PUT_LINE('Estatus: ' || v_status);
        DBMS_OUTPUT.PUT_LINE('Precio: ' || v_precio);
    ELSE
        DBMS_OUTPUT.PUT_LINE('No se encontró el producto indicado.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al leer el producto: ' || SQLERRM);
END;
