### ISSUE TITLE
(TipoProducto) SP_CrearTipoProducto

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#25]
Debe tener los siguentes parametros:
-[ ] Nombre
-[ ] Descripcion 

y crear el tipoproducto

**Comment by CrisPicado** [comment]
CREATE OR REPLACE PROCEDURE SP_CrearTipoProducto(
    p_Nombre IN VARCHAR,
    p_Descripcion IN VARCHAR
) AS
BEGIN
    IF p_Nombre IS NULL OR p_Descripcion IS NULL THEN
        DBMS_OUTPUT.PUT_LINE('El nombre y la descripción del tipo de producto no pueden ser NULL.');
    ELSE
        INSERT INTO TipoProducto (Nombre, Descripcion)
        VALUES (p_Nombre, p_Descripcion);
        DBMS_OUTPUT.PUT_LINE('Tipo de producto creado con éxito.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al crear el tipo de producto: ' || SQLERRM);
END;
