### ISSUE TITLE
(Producto) View_LeerProducto (TODOS)

### ISSUE THREAD

**Issue by Sebastian2207** [electromilitary45/PUFI_LenguajesBD#26]
Debe de mostrar los siguientes parametros:
-[ ] idProductos
-[ ] idTipoProducto
-[ ] nombre
-[ ] descripcion
-[ ] stock
-[ ] estatus
-[ ] precio

**Comment by CrisPicado** [comment]
CREATE OR REPLACE VIEW Vista_LeerProductos AS
SELECT IDPRODUCTO "ID", IDTIPOPRODUCTO "CATEGORIA", NOMBRE, DESCRIPCION, STOCK, ESTATUS, PRECIO
FROM PRODUCTO
