### ISSUE TITLE
(TipoProducto) SP_EditarTipoProducto

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#27]
Debe recibir los siguente parametros:
- [ ] idTipoProducto
- [ ] Nombre
- [ ] Descripcion

y realizar la edicion

**Comment by CrisPicado** [comment]
CREATE OR REPLACE PROCEDURE SP_EditarTipoProducto(
    p_idTipoProducto IN NUMBER,
    p_Nombre IN VARCHAR,
    p_Descripcion IN VARCHAR
) AS
    v_cuenta NUMBER;
BEGIN
    -- Verificar si el TipoProducto existe
    SELECT COUNT(*) INTO v_cuenta
    FROM TipoProducto
    WHERE idTipoProducto = p_idTipoProducto;
    
    IF v_cuenta = 0 THEN
        DBMS_OUTPUT.PUT_LINE('El TipoProducto con el ID indicado no existe, no se puede realizar la edición.');
    ELSE
        -- Realizar la edición del TipoProducto
        UPDATE TipoProducto
        SET Nombre = p_Nombre,
            Descripcion = p_Descripcion
        WHERE idTipoProducto = p_idTipoProducto;
        
        DBMS_OUTPUT.PUT_LINE('Tipo de producto editado con éxito.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al editar el tipo de producto: ' || SQLERRM);
END;
