### ISSUE TITLE
(Producto) SP_LeerResenaAceptadaPorProducto

### ISSUE THREAD

**Issue by Sebastian2207** [electromilitary45/PUFI_LenguajesBD#28]
Debe de recibir el parametro:
-[ ] idProducto

Debe de mostrar los siguientes parametros de la tabla usuario:
-[ ] nombre
-[ ] primApellido
-[ ] segApellido
-[ ] correo

Debe de mostrar los siguientes datos de la tabla producto
-[ ] nombre

Debe de mostrar los siguientes datos de la tabla resenna
-[ ] descripcion

**Comment by CrisPicado** [comment]
Para el siguiente issue sugiero lo siguiente, primeramente crear una vista que muestre un resumen general de las reseñas que realizan los clientes sobre los productos, la vista realiza una consulta en la tabla Reseña y un INNER JOIN con las tablas de Producto y Usuario.

CREATE OR REPLACE VIEW Vista_Resennas AS
SELECT u.nombre || ' '|| u.primapellido || ' '|| u.segapellido "CLIENTE", u.correo,r.idproducto ,p.nombre "PRODUCTO", r.descripcion
FROM RESENNA r
INNER JOIN PRODUCTO p ON r.idproducto = p.idproducto
INNER JOIN USUARIO u ON r.idusuario = u.idusuario

Posterior, se crea un SP para obtener cuáles son las reseñas que realizan los clientes para un producto en específico, el SP hace uso de la vista anteriormente creada para filtrarlo en base al parámetro del ID del producto, además que utiliza un cursor para que recorra y logre mostrar todas las reseñas que tiene un producto en específico

CREATE OR REPLACE PROCEDURE SP_ResennaProducto(
    p_idProducto IN NUMBER
) AS
    v_contador NUMBER;
    v_cliente VARCHAR(200);
    v_correo VARCHAR(150);
    v_producto VARCHAR(100);
    v_descripcion VARCHAR(300);
    CURSOR c_resennas IS 
        SELECT CLIENTE, CORREO, PRODUCTO, DESCRIPCION
        FROM Vista_Resennas v
        WHERE v.idproducto = p_idProducto;
BEGIN
    SELECT COUNT(*) INTO v_contador
    FROM Vista_Resennas v
    WHERE v.idproducto = p_idProducto;
    
    IF v_contador > 0 THEN
        OPEN c_resennas;
        LOOP
            FETCH c_resennas INTO v_cliente, v_correo, v_producto, v_descripcion;
            EXIT WHEN c_resennas%NOTFOUND;
            
            DBMS_OUTPUT.PUT_LINE('------------------------------');
            DBMS_OUTPUT.PUT_LINE('Cliente: ' || v_cliente);
            DBMS_OUTPUT.PUT_LINE('Correo: ' || v_correo);
            DBMS_OUTPUT.PUT_LINE('Producto: ' || v_producto);
            DBMS_OUTPUT.PUT_LINE('Descripción: ' || v_descripcion);
        
        END LOOP;
        CLOSE c_resennas;
        DBMS_OUTPUT.PUT_LINE('------------------------------');
    ELSE
        DBMS_OUTPUT.PUT_LINE('El producto indicado no cuenta con reseñas.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al leer las reseñas del producto: ' || SQLERRM);
END;
