### ISSUE TITLE
(ROL) Sp_LeerRol

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#3]
Debe Crear un procedimiento que reciba como parametros:

 - [ ] idRol

Debe realizar un select completo con el 'idRol' recibido por parametros.

**Comment by CrisPicado** [comment]
CREATE OR REPLACE PROCEDURE SP_LeerRol(
    p_idRol IN NUMBER
) AS
    v_cuenta NUMBER;
    v_nombre ROL.NOMBRE%TYPE;
BEGIN
    -- Verificar si el ID del rol existe
    SELECT COUNT(*) INTO v_cuenta
    FROM ROL
    WHERE IDROL = p_idRol;
    
    IF v_cuenta = 0 THEN
        -- El ID del rol no existe, mostrar un mensaje de error
        DBMS_OUTPUT.PUT_LINE('Error: El ID del rol no existe.');
    ELSE
        -- El ID del rol existe, obtener el nombre del rol
        SELECT NOMBRE INTO v_nombre
        FROM ROL
        WHERE IDROL = p_idRol;
        
        -- Mostrar los datos del rol
        DBMS_OUTPUT.PUT_LINE('ID Rol: ' || p_idRol || ' - Nombre: ' || v_nombre);
    END IF;
END;
