### ISSUE TITLE
(TipoProducto) Vista LeerTipoProductos

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#35]
Debe realizar una vista donde se muestren todos los datos

**Comment by CrisPicado** [comment]
CREATE VIEW Vista_TipoProductos AS 
SELECT IDTIPOPRODUCTO "ID",NOMBRE "NOMBRE",DESCRIPCION "DESCRIPCION"
FROM TIPOPRODUCTO
