### ISSUE TITLE
(TipoProducto) SP_LeerVategoria (UNICO)

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#36]
-Debe recibir como parametro:
-[ ] idTipoProducto

y realizar el Select

**Comment by CrisPicado** [comment]
CREATE OR REPLACE PROCEDURE SP_LeerTipoProducto(
    p_idTipoProducto IN NUMBER
)
AS
    v_contador NUMBER;
    v_id NUMBER;
    v_nombre VARCHAR(100);
    v_descripcion VARCHAR(200);
BEGIN
    SELECT COUNT(*) INTO v_contador
    FROM Vista_TipoProductos v
    WHERE v."ID" = p_idTipoProducto;

    IF v_contador > 0 THEN
        SELECT "ID", "NOMBRE", "DESCRIPCION" 
        INTO v_id, v_nombre, v_descripcion
        FROM Vista_TipoProductos
        WHERE "ID" = p_idTipoProducto; 
        
        DBMS_OUTPUT.PUT_LINE('---Datos del tipo de producto---');
        DBMS_OUTPUT.PUT_LINE('ID: '|| v_id);
        DBMS_OUTPUT.PUT_LINE('Nombre: '|| v_nombre);
        DBMS_OUTPUT.PUT_LINE('Descripción: '|| v_descripcion);
    ELSE
        DBMS_OUTPUT.PUT_LINE('No se encontró el tipo de producto indicado.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al leer el tipo de producto: ' || SQLERRM);
END;
