### ISSUE TITLE
(ROL) Trigger_VerRolCreado/Editado

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#6]
Debe crear un trigger, que al crear/editar un rol, muestra el rol creado/editado.

**Comment by CrisPicado** [comment]
(ROL) Trigger_VerRolCreado/Editado#6
--Debe crear un trigger, que al crear/editar un rol, muestra el rol creado/editado.


CREATE OR REPLACE TRIGGER trg_insertar_rol
AFTER INSERT ON Rol
FOR EACH ROW
DECLARE
    v_idRol rol.idRol%TYPE;
    v_nombre rol.nombre%TYPE;
BEGIN
    v_idRol := :new.idRol;
    v_nombre := :new.nombre;
    
    DBMS_OUTPUT.PUT_LINE('Rol insertado - ID: ' || v_idRol || ', Nombre: ' || v_nombre);
END;


CREATE OR REPLACE TRIGGER trg_editar_rol
AFTER UPDATE ON rol
FOR EACH ROW
DECLARE
    -- Variables para almacenar los datos del rol
    v_idRol rol.idRol%TYPE;
    v_nombre rol.nombre%TYPE;
BEGIN
    -- Obtener los datos actualizados del rol
    v_idRol := :new.idRol;
    v_nombre := :new.nombre;

    -- Devolver los datos actualizados del rol
    DBMS_OUTPUT.PUT_LINE('Rol actualizado - ID: ' || v_idRol || ', Nombre: ' || v_nombre);
END;
