### ISSUE TITLE
(USUARIO) SP_CrearUsuario

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#7]
Debe Crear un procedimiento que reciba como parametros:
 - [ ] nombre
 - [ ] primApellido
 - [ ] segApellido
 - [ ] cedula
 - [ ] correo
 - [ ] contrasena
 - [ ] idRol
 
 Al tratar de crear se debe verificar por medio de la cedula, si existe no se debe registrar y debe retornar un mensaje 'El usuario ya fue creado previamente'

**Comment by CrisPicado** [comment]
Como sugerencia para mantener la integridad de los registros de los usuarios, se adiciona una validación en el SP que se encarga de validar, previo al registro de usuario, si el idrol indicado existe.

**Comment by CrisPicado** [comment]
CREATE OR REPLACE PROCEDURE SP_CrearUsuario(
    p_nombre IN VARCHAR,
    p_primApellido IN VARCHAR,
    p_segApellido IN VARCHAR,
    p_cedula IN VARCHAR,
    p_correo IN VARCHAR,
    p_contrasenna IN VARCHAR,
    p_idRol IN NUMBER
)
AS
    cuentaCedula NUMBER;
    cuentaRol NUMBER;
BEGIN
    SELECT COUNT(*) INTO cuentaCedula FROM Usuario u
    WHERE u.cedula = p_cedula;
    
    SELECT COUNT(*) INTO cuentaRol FROM Rol r
    WHERE r.idrol = p_idRol;
    
    IF cuentaRol = 0 THEN
        DBMS_OUTPUT.PUT_LINE('El rol indicado no existe, no es posible crear el usuario con un rol inexistente.');
    ELSIF cuentaCedula > 0 THEN
        DBMS_OUTPUT.PUT_LINE('El usuario ya fue creado previamente.');
    ELSE
        INSERT INTO Usuario (nombre, primapellido, segapellido, cedula, correo, contrasenna, idrol, iddireccion)
        VALUES (p_nombre, p_primApellido, p_segApellido, p_cedula, p_correo, p_contrasenna, p_idRol,0);
        DBMS_OUTPUT.PUT_LINE('Usuario creado con éxito.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al crear el usuario: ' || SQLERRM);
END;
