### ISSUE TITLE
(Usuario) View UsuariosPorRol

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#8]

**Comment by CrisPicado** [comment]
CREATE OR REPLACE VIEW V_UsuariosConRol AS
SELECT u.idUsuario "ID Usuario", u.nombre "Nombre", u.primApellido "Primer Apellido", u.segApellido "Segundo Apellido", u.cedula "Cédula", u.correo "Correo", u.contrasenna "Contraseña", r.nombre AS "Rol"
FROM Usuario u
INNER JOIN Rol r ON u.idRol = r.idRol;
