### ISSUE TITLE
(USUARIO) Editar Usuario

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/PUFI_LenguajesBD#9]
Debe recibir como parametros 
-[ ] idUsuario
-[ ] nombre
-[ ] primApellido
-[ ] segApellido
-[ ] cedula
-[ ] correo
-[ ] contrasenna
-[ ] idRol
-[ ] idDireccion

y actualizar el usuario

**Comment by CrisPicado** [comment]
CREATE OR REPLACE PROCEDURE SP_EditarUsr(
    p_idUsr IN NUMBER,
    p_nombre IN VARCHAR,
    p_primApellido IN VARCHAR,
    p_segApellido IN VARCHAR,
    p_cedula IN VARCHAR,
    p_correo IN VARCHAR,
    p_contrasenna IN VARCHAR,
    p_idRol IN NUMBER, 
    p_idDireccion IN NUMBER
)AS
    cuentaUsr NUMBER;
    cuentaCedula NUMBER;
    cuentaRol NUMBER;
BEGIN
    --Valida si el usuario existe
    SELECT COUNT(*) INTO cuentaUsr FROM Usuario u
    WHERE u.idUsuario = p_idUsr;

    --valida si la cedula existe y está asignada a otra persona
    SELECT COUNT(*) INTO cuentaCedula FROM Usuario u
    WHERE u.cedula = p_cedula AND u.idUsuario != p_idUsr;
    
    --valida existencia del rol
    SELECT COUNT(*) INTO cuentaRol FROM Rol r
    WHERE r.idrol = p_idRol;
    
    IF cuentaUsr = 0 THEN
        DBMS_OUTPUT.PUT_LINE('El usuario indicado no existe.');
    ELSIF cuentaRol = 0 THEN
        DBMS_OUTPUT.PUT_LINE('El rol indicado no existe, no es posible editar el usuario con un rol inexistente.');
    ELSIF cuentaCedula > 0 THEN
        DBMS_OUTPUT.PUT_LINE('La cédula ingresada pertenece a otro usuario existente.');
    ELSE
        UPDATE Usuario SET
        nombre = p_nombre,
        primapellido = p_primApellido,
        segapellido = p_segApellido,
        cedula = p_cedula,
        correo = p_correo,
        contrasenna = p_contrasenna,
        idrol = p_idRol
        WHERE idUsuario = p_idUsr;
        
        DBMS_OUTPUT.PUT_LINE('Usuario editado con éxito.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al editar el usuario: ' || SQLERRM);
END;
